=== 545473750/zswxsqxt/src/main/freesql/cn/com/ebmp/freesql/builder/xml/freesql-3-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT mapper (resultMap* | parameterMap* | sql* | insert* | update* | delete* | select* )+>
<!ATTLIST mapper
xmlns:fo CDATA #IMPLIED
namespace CDATA #IMPLIED
>


<!ELEMENT parameterMap EMPTY>
<!ATTLIST parameterMap
id CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT resultMap (result*)>
<!ATTLIST resultMap
id CDATA #REQUIRED
type CDATA #REQUIRED
>


<!ELEMENT result EMPTY>
<!ATTLIST result
property CDATA #REQUIRED
column CDATA #IMPLIED
javaType CDATA #IMPLIED
>


<!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST select
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
resultMap CDATA #IMPLIED
resultType CDATA #IMPLIED
autoMapping CDATA #IMPLIED
>

<!ELEMENT insert (#PCDATA |  include | trim | where | set | foreach | choose | if)*>
<!ATTLIST insert
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
>

<!ELEMENT update (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST update
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
>

<!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST delete
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterType CDATA #IMPLIED
>

<!-- Dynamic -->

<!ELEMENT include EMPTY>
<!ATTLIST include
refid CDATA #REQUIRED
>

<!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST sql
id CDATA #REQUIRED
>

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST trim
prefix CDATA #IMPLIED
prefixOverrides CDATA #IMPLIED
suffix CDATA #IMPLIED
suffixOverrides CDATA #IMPLIED
>
<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST foreach
collection CDATA #REQUIRED
item CDATA #IMPLIED
index CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
separator CDATA #IMPLIED
>

<!ELEMENT choose (when* , otherwise?)>
<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST when
test CDATA #REQUIRED
>
<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST if
test CDATA #REQUIRED
>

=== 545473750/zswxsqxt/src/main/freesql/service_core.mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//freesql.org//DTD Mapper 3.0//EN"  "http://freesql.org/dtd/freesql-3-mapper.dtd">
<mapper namespace="servicecore">
	<resultMap id="customerInfoMapping" type="com.zswxsqxt.core.model.CustomerInfo">
		<id column="id" property="id"/>
		<result column="license_num" property="licenseNum" />
		<result column="customer_num" property="customerNum" />
		<result column="contract_num" property="contractNum" />
		<result column="province" property="province" />
		<result column="district" property="district" />
		<result column="post_code" property="postCode" />
		<result column="unit_name" property="unitName" />
		<result column="unit_address" property="unitAddress" />
		<result column="customer_type" property="customerType" />
		<result column="contact_person" property="contactPerson" />
		<result column="phone_number" property="phoneNumber" />
		<result column="fax_number" property="faxNumber" />
		<result column="open_terminal" property="openTerminal" />
		<result column="signing_terminal" property="signingTerminal" />
		<result column="adjustment_terminal" property="adjustmentTerminal" />
		<result column="protocol_cycle" property="protocolCycle" />
		<result column="channel_price" property="channelPrice" />
		<result column="total_price" property="totalPrice" />
		<result column="special_money" property="specialMoney" />
		<result column="free_days" property="freeDays" />
		<result column="remark" property="remark" />
		<result column="ts" property="ts" />
		<result column="change_time" property="changeTime" />
		<collection property="nodes" resultMap="instanceNodeMapping" />
	</resultMap>
	
	<!--
	<resultMap id="sysUser" type="com.opendata.organiz.model.User">
		<id column="user_id" property="id" />
		<result column="loginname" property="loginname" />
		<result column="password" property="password" />
		<result column="username" property="username" />
		<result column="ts" property="ts" />
		<result column="df" property="df" />
		<result column="isLeave" property="isLeave" />
		<result column="abledFlag" property="abledFlag" />
		<result column="userNum" property="userNum" />
		<result column="cardType" property="cardType" />
		<result column="passport" property="passport" />
		<result column="IDNum" property="IDNum" />
		<result column="source" property="source" />
		<result column="module" property="module" />
		<result column="personType" property="personType" />
		<result column="unitId" property="unitId" />
		<result column="unitName" property="unitName" />
	</resultMap> -->
	
	<resultMap id="instanceNodeMapping" type="com.zswxsqxt.wf.model.WfInstanceNode">
		<id column="node_id" property="id" />
		<result column="name" property="name" />
		<result column="orderNum" property="orderNum" />
		<result column="description" property="description" />
		<result column="ts" property="ts" />
		<result column="auditValue" property="auditValue" />
		<result column="auditorNum" property="auditorNum" />
	</resultMap>

	<select id="customerList" parameterType="com.zswxsqxt.core.query.CustomerInfoQuery" resultMap="customerInfoMapping">
		SELECT cf.id id,cf.license_num, cf.unit_name, node.id node_id, COUNT(node.id) auditorNum, SUM(au.result) auditValue 
		  FROM core_customerinfo cf 
		  left join wf_Instance ins on cf.id=ins.target_id
		  left join wf_instance_node node on ins.id=node.instanceId
		  left join wf_instance_participan ip on ip.actId=node.id
		  left join wf_instance_audit au on au.iaId=node.id and au.auditUserId=ip.refId
		  group by cf.id,cf.license_num, cf.unit_name, node.id
	</select>
</mapper>

=== 545473750/zswxsqxt/src/main/freesql/jc.mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//freesql.org//DTD Mapper 3.0//EN"  "http://freesql.org/dtd/freesql-3-mapper.dtd">
<mapper namespace="jc">
	<!--监察任务上报 ${sqlDutyUntils}   -->
	<select id="findSbTaskReport" parameterType="java.util.HashMap"  resultType="com.zg.jc.beans.TaskReportBeans">
		select  
		  task.id,
		  task.year,
		  projectType.typeOne ,
		  projectType.typeTwo ,
		  task.seq,
		  task.content,
		  task.finishDateLimit,
		
		   ( select isnull(max(proceePercent),0) 
		   		from jc_taskReport 
		   		where 
		   	  		reportDate= ( select max(reportDate) reportDate from jc_taskReport jc where jc.taskId=task.id <if test="dutyUntil != null and dutyUntil!='' "> and jc.dutyUntil = '${dutyUntil}'</if> ) 
		   	  		and taskId=task.id  
		   	  		<if test="dutyUntil != null and dutyUntil!='' "> and dutyUntil = '${dutyUntil}'</if>
		   ) as proceePercent,
		  task.state,
		(
		select isnull(count(tr.id),0)  from jc_taskReport as tr 
		where 
		  tr.nearReportDate &lt;= #{sysDate} and tr.planReportDate &gt;= #{sysDate} and 
		  tr.state=0 and tr.taskId=task.id
		  <if test="dutyUntil != null and dutyUntil!='' ">
				and tr.dutyUntil = '${dutyUntil}'
		  </if>
		) as yellowColor,
		
		(
		select isnull(count(tr.id),0)  from jc_taskReport as tr 
		where 
		 tr.planReportDate &lt;= #{sysDate} and 
		  tr.state=0 and 
		  tr.taskId=task.id
		  <if test="dutyUntil != null and dutyUntil!='' ">
				and tr.dutyUntil = '${dutyUntil}'
		  </if>
		) as redColor
		
		from 
		   jc_task as task,
    	   jc_projectType as projectType 
		
		<where>
		 	task.projectTypeId=projectType.id 
		 	
			 and   charindex('${dutyUntil}',task.dutyUnits)>0
			
			<if test="year != null">
				and task.year = ${year}
			</if>
			<if test="state != null">
				and task.state = ${state}
			</if>
			<if test="projectTypeId != null and projectTypeId != ''">
				and projectType.id = '${projectTypeId}'
			</if>
			<if test="content != null and content != ''">
				and task.content like '${content}%'
			</if>
		</where> 
		order by task.state, projectType.typeOne,cast(projectType.seq as int),task.seqnumber
	</select>
	
	
	<!--监察任务督查-->
	<select id="findDcTaskReport" parameterType="java.util.HashMap"  resultType="com.zg.jc.beans.TaskReportBeans">
		select  
		  task.id,
		  task.year,
		  projectType.typeOne ,
		  projectType.typeTwo ,
		  task.seq,
		  task.content,
		  task.finishDateLimit,
		
		   (select avg(proceePercent) from 
			(
			  select  
				rt.dutyUntil,
				(select isnull(max(proceePercent),0) from  jc_taskReport where taskId=task.id and  dutyUntil=rt.dutyUntil ) as proceePercent
			from 
			   jc_taskReport as rt 
			where 
			   rt.taskId=task.id 
			group by 
			   dutyUntil
			) as tmpTable) as proceePercent,
		  task.state,
		(
		select isnull(count(tr.id),0)  from jc_taskReport as tr 
		where 
		  tr.nearReportDate &lt;= #{sysDate} and tr.planReportDate &gt;= #{sysDate} and 
		  tr.state=0 and tr.taskId=task.id
		) as yellowColor,
		
		(
		select isnull(count(tr.id),0)  from jc_taskReport as tr 
		where 
		 tr.planReportDate &lt;= #{sysDate} and 
		  tr.state=0 and 
		  tr.taskId=task.id
		) as redColor,
		(
		select count(*) from jc_taskReport as tr 
		 where
		 tr.state=1 and 
		 tr.taskId=task.id and
		 tr.modifyState = 1
		 ) as modifyState
		
		from 
		   jc_task as task,
    	   jc_projectType as projectType 
		<where>
		 	task.projectTypeId=projectType.id 
			<if test="year != null">
				and task.year = ${year}
			</if>
			<if test="state != null">
				and task.state = ${state}
			</if>
			<if test="projectTypeId != null and projectTypeId != ''">
				and projectType.id = '${projectTypeId}'
			</if>
			<if test="content != null and content != ''">
				and task.content like '${content}%'
			</if>
			<if test="dutyUntil != null and dutyUntil!='' ">
				and   charindex('${dutyUntil}',task.dutyUnits)>0 
			 </if>
			 <if test="dutyLeader != null and dutyLeader!='' ">
				and   charindex('${dutyLeader}',task.dutyLeaders)>0 
			 </if>
			 
		</where> 
		order by task.state, projectType.typeOne,cast(projectType.seq as int),task.seqnumber
	</select>
	
</mapper>
